root: true
extends:
  - airbnb-base
  - prettier
  - plugin:jest/recommended
  - plugin:@typescript-eslint/recommended
#parser: babel-eslint
parser: "@typescript-eslint/parser"
plugins:
  - jest
  - prettier
  - "@typescript-eslint"
rules:
  prettier/prettier:
    - error
    -
      trailingComma: es5
      singleQuote: true
  class-methods-use-this: off
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  no-useless-constructor: 'off'
  "@typescript-eslint/no-useless-constructor":
    - error
  no-shadow: "off"
  no-any: 'off'
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/explicit-module-boundary-types":
    - off
  import/no-extraneous-dependencies:
    - error
    - 
      devDependencies:
        - "**/*.test.ts"
        - "**/*.spec.ts"
  import/no-unresolved:
    - error
    - 
      ignore:
        - "aws-lambda"
  import/prefer-default-export: "off"
  max-classes-per-file: "off"
  # disable no-use-before-define
  no-use-before-define: "off"
  
env:
  node: true
  jest/globals: true
  commonjs: true
settings:
    "import/resolver":
      node:
        extensions:
          - ".js"
          - ".jsx"
          - ".ts"
          - ".tsx"
